version: '3.8'
services:
  frontend:
    build:
      context: ./sdis-emergency/Emergency-Manager/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  emergency-manager:
    build:
      context: ./sdis-emergency/Emergency-Manager
      dockerfile: Dockerfile
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://database:5432/emergency_db
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=admin
    depends_on:
      - database
    ports:
      - "8080:8080"

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: emergency_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
